name: xtermjs
# When the 'permissions' key is specified, unspecified permission scopes (e.g.,
# actions, checks, etc.) are set to no access (none).
permissions:
  contents: read
on:
  workflow_dispatch:

jobs:
  xtermjs:
    runs-on: ubuntu-latest

    steps:
      - name: Zip
        run: |
          npm install @xterm/xterm @xterm/addon-canvas
          mkdir xtermjs
          cp \
            node_modules/@xterm/xterm/lib/xterm.js \
            node_modules/@xterm/xterm/css/xterm.css \
            node_modules/@xterm/addon-canvas/lib/addon-canvas.js \
            xtermjs

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: xtermjs
          path: xtermjs
